//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zapravka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile
    {
        public double TankVolume { get; set; }
        public double MaxTankVolume { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public int Id { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
