//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zapravka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banknote
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int BanknoteTypeId { get; set; }
        public int ClientId { get; set; }
    
        public virtual BanknoteType BanknoteType { get; set; }
        public virtual Client Client { get; set; }
    }
}
